package catalog_test

import (
	"go/format"
	"testing"

	"github.com/codefly-dev/saas-sdk-go/settings/catalog"
)

var sample = []catalog.Contribution{
	{
		Namespace:   "appearance",
		ProtoImport: "contributed/appearance/v1/appearance.proto",
		Message:     "saas.appearance.v1.Appearance",
		FieldName:   "appearance",
		FieldNumber: 1,
	},
	{
		Namespace:   "billing",
		ProtoImport: "contributed/billing/v1/billing.proto",
		Message:     "saas.billing.v1.Billing",
		FieldName:   "billing",
		FieldNumber: 2,
	},
}

func TestRenderProto(t *testing.T) {
	want := `// Code generated by module-compose. DO NOT EDIT.
syntax = "proto3";

package saas.composed.settings.v1;

import "contributed/appearance/v1/appearance.proto";
import "contributed/billing/v1/billing.proto";

message Settings {
  saas.appearance.v1.Appearance appearance = 1;
  saas.billing.v1.Billing billing = 2;
}
`
	if got := catalog.RenderProto(sample); got != want {
		t.Fatalf("RenderProto mismatch:\n got: %q\nwant: %q", got, want)
	}
}

func TestRenderGo(t *testing.T) {
	want := `// Code generated by module-compose. DO NOT EDIT.
package settingscatalog

type Field struct {
	Namespace string
	Name string
	Number int
	Message string
}

var fields = [...]Field{
	{Namespace: "appearance", Name: "appearance", Number: 1, Message: "saas.appearance.v1.Appearance"},
	{Namespace: "billing", Name: "billing", Number: 2, Message: "saas.billing.v1.Billing"},
}

func Fields() []Field {
	return append([]Field(nil), fields[:]...)
}
`
	got := catalog.RenderGo(sample)
	if got != want {
		t.Fatalf("RenderGo mismatch:\n got: %q\nwant: %q", got, want)
	}
	if _, err := format.Source([]byte(got)); err != nil {
		t.Fatalf("RenderGo output is not valid Go source: %v", err)
	}
}

func TestRenderTypeScript(t *testing.T) {
	want := `// Code generated by module-compose. DO NOT EDIT.
export const SETTINGS_FIELDS = Object.freeze([
	{ namespace: "appearance", name: "appearance", number: 1, message: "saas.appearance.v1.Appearance" },
	{ namespace: "billing", name: "billing", number: 2, message: "saas.billing.v1.Billing" },
] as const);
`
	if got := catalog.RenderTypeScript(sample); got != want {
		t.Fatalf("RenderTypeScript mismatch:\n got: %q\nwant: %q", got, want)
	}
}

func TestRenderersHandleNoContributions(t *testing.T) {
	if got := catalog.RenderProto(nil); got == "" {
		t.Fatal("RenderProto returned empty output")
	}
	got := catalog.RenderGo(nil)
	if _, err := format.Source([]byte(got)); err != nil {
		t.Fatalf("empty RenderGo output is not valid Go source: %v", err)
	}
	if got := catalog.RenderTypeScript(nil); got == "" {
		t.Fatal("RenderTypeScript returned empty output")
	}
}
