// Package catalog renders language-specific typed-settings catalogs from a
// module's declared settings contributions. The render functions are the
// reusable half of module-compose: a module declares its concrete settings
// proto plus contributions and gets Go, TypeScript, and proto catalogs
// generated uniformly, instead of re-implementing the renderers in-repo.
//
// The functions are pure and schema-agnostic: they turn ordered contributions
// into deterministic source text and take no dependency on any generated
// schema. RenderGo emits unformatted Go source; run it through go/format
// before writing, as module-compose does.
//
// The renderers assume their input is already valid and will faithfully emit
// invalid output for invalid input. Callers outside module-compose must run
// Validate (or Contribution.Validate) first; module-compose validates as part
// of composition before rendering.
package catalog

import (
	"fmt"
	"strings"
)

// ComposedProtoPackage is the fixed proto package of the composed Settings
// message across every module. It is a platform contract, not a per-module
// choice: the SDK ships generated bindings for it at gen/saas/composed/settings/v1,
// so RenderProto emits this exact package rather than accepting an override.
const ComposedProtoPackage = "saas.composed.settings.v1"

// GoCatalogPackage is the fixed Go package name of the generated settings
// catalog every module compiles. RenderGo emits this exact package.
const GoCatalogPackage = "settingscatalog"

// Contribution is one module's settings field in the composed catalog. It is
// the projection of a module.package.codefly.yaml settings contribution that
// the renderers need: the namespace it owns, the proto file to import, the
// fully qualified message type, and the field name/number it occupies in the
// composed Settings message.
type Contribution struct {
	Namespace   string
	ProtoImport string
	Message     string
	FieldName   string
	FieldNumber int
}

// RenderProto renders the composed settings proto: one import and one field per
// contribution, wrapped in the composed Settings message. Input must be valid;
// see Validate.
func RenderProto(contributions []Contribution) string {
	var body strings.Builder
	fmt.Fprintf(&body, "// Code generated by module-compose. DO NOT EDIT.\nsyntax = \"proto3\";\n\npackage %s;\n\n", ComposedProtoPackage)
	for _, contribution := range contributions {
		fmt.Fprintf(&body, "import %q;\n", contribution.ProtoImport)
	}
	body.WriteString("\nmessage Settings {\n")
	for _, contribution := range contributions {
		fmt.Fprintf(&body, "  %s %s = %d;\n", contribution.Message, contribution.FieldName, contribution.FieldNumber)
	}
	body.WriteString("}\n")
	return body.String()
}

// RenderGo renders the Go settings catalog. The output is unformatted source;
// callers run it through go/format before writing to disk. Input must be valid;
// see Validate.
func RenderGo(contributions []Contribution) string {
	var body strings.Builder
	fmt.Fprintf(&body, "// Code generated by module-compose. DO NOT EDIT.\npackage %s\n\ntype Field struct {\n\tNamespace string\n\tName string\n\tNumber int\n\tMessage string\n}\n\nvar fields = [...]Field{\n", GoCatalogPackage)
	for _, contribution := range contributions {
		fmt.Fprintf(&body, "\t{Namespace: %q, Name: %q, Number: %d, Message: %q},\n", contribution.Namespace, contribution.FieldName, contribution.FieldNumber, contribution.Message)
	}
	body.WriteString("}\n\nfunc Fields() []Field {\n\treturn append([]Field(nil), fields[:]...)\n}\n")
	return body.String()
}

// RenderTypeScript renders the TypeScript settings catalog as a frozen array of
// field descriptors. Input must be valid; see Validate.
func RenderTypeScript(contributions []Contribution) string {
	var body strings.Builder
	body.WriteString("// Code generated by module-compose. DO NOT EDIT.\nexport const SETTINGS_FIELDS = Object.freeze([\n")
	for _, contribution := range contributions {
		fmt.Fprintf(&body, "\t{ namespace: %q, name: %q, number: %d, message: %q },\n", contribution.Namespace, contribution.FieldName, contribution.FieldNumber, contribution.Message)
	}
	body.WriteString("] as const);\n")
	return body.String()
}
