// Package catalog renders language-specific typed-settings catalogs from a
// module's declared settings contributions. The render functions are the
// reusable half of module-compose: a module declares its concrete settings
// proto plus contributions and gets Go, TypeScript, and proto catalogs
// generated uniformly, instead of re-implementing the renderers in-repo.
//
// The functions are pure and schema-agnostic: they turn ordered contributions
// into deterministic source text and take no dependency on any generated
// schema. RenderGo emits unformatted Go source; run it through go/format
// before writing, as module-compose does.
package catalog

import (
	"fmt"
	"strings"
)

// Contribution is one module's settings field in the composed catalog. It is
// the projection of a module.package.codefly.yaml settings contribution that
// the renderers need: the namespace it owns, the proto file to import, the
// fully qualified message type, and the field name/number it occupies in the
// composed Settings message.
type Contribution struct {
	Namespace   string
	ProtoImport string
	Message     string
	FieldName   string
	FieldNumber int
}

// RenderProto renders the composed settings proto: one import and one field per
// contribution, wrapped in the composed Settings message.
func RenderProto(contributions []Contribution) string {
	var body strings.Builder
	body.WriteString("// Code generated by module-compose. DO NOT EDIT.\nsyntax = \"proto3\";\n\npackage saas.composed.settings.v1;\n\n")
	for _, contribution := range contributions {
		fmt.Fprintf(&body, "import %q;\n", contribution.ProtoImport)
	}
	body.WriteString("\nmessage Settings {\n")
	for _, contribution := range contributions {
		fmt.Fprintf(&body, "  %s %s = %d;\n", contribution.Message, contribution.FieldName, contribution.FieldNumber)
	}
	body.WriteString("}\n")
	return body.String()
}

// RenderGo renders the Go settings catalog. The output is unformatted source;
// callers run it through go/format before writing to disk.
func RenderGo(contributions []Contribution) string {
	var body strings.Builder
	body.WriteString("// Code generated by module-compose. DO NOT EDIT.\npackage settingscatalog\n\ntype Field struct {\n\tNamespace string\n\tName string\n\tNumber int\n\tMessage string\n}\n\nvar fields = [...]Field{\n")
	for _, contribution := range contributions {
		fmt.Fprintf(&body, "\t{Namespace: %q, Name: %q, Number: %d, Message: %q},\n", contribution.Namespace, contribution.FieldName, contribution.FieldNumber, contribution.Message)
	}
	body.WriteString("}\n\nfunc Fields() []Field {\n\treturn append([]Field(nil), fields[:]...)\n}\n")
	return body.String()
}

// RenderTypeScript renders the TypeScript settings catalog as a frozen array of
// field descriptors.
func RenderTypeScript(contributions []Contribution) string {
	var body strings.Builder
	body.WriteString("// Code generated by module-compose. DO NOT EDIT.\nexport const SETTINGS_FIELDS = Object.freeze([\n")
	for _, contribution := range contributions {
		fmt.Fprintf(&body, "\t{ namespace: %q, name: %q, number: %d, message: %q },\n", contribution.Namespace, contribution.FieldName, contribution.FieldNumber, contribution.Message)
	}
	body.WriteString("] as const);\n")
	return body.String()
}
